version: "3"
services:
  service_registry:
    image: service-registry
    ports:
      - "8761:8761"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.5
        
  onboarding_associate_ui:
    image: 7434e345a84d
    ports:
      - "3000:3000"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.13
    depends_on:
      - token_service

  token_service:
    image: token-service
    ports:
      - "9099:9099"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.6
    depends_on:
      - service_registry
      - mongo_db

  mongo_db:
    image: 4130848d45a9
    ports:
      - "27017:27017"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.7
         
  cloud_gateway_service:
    image: cloud-gateway-service
    ports:
      - "9191:9191"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.8
    depends_on:
      - service_registry

  cloud_config_service:
    image: cloud-config-service
    ports:
      - "9296:9296"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.9
    depends_on:
      - service_registry
        
  onboarding_task_service:
    image: onboarding-task-service
    ports:
      - "9094:9094"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.10
    depends_on:
      - service_registry
      - mongo_db
      
  associate_service:
    image: associate-service
    ports:
      - "9092:9092"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.11
    depends_on:
      - service_registry
      - cloud_gateway_service
      - cloud_config_service
      - mongo_db
      
  skill-service:
    image: skill-service
    ports:
      - "9091:9091"
    networks:
      vpcbr: 
        ipv4_address: 10.5.0.12
    depends_on:
      - service_registry
      - mongo_db

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1